### ISSUE TITLE
Creating Frontend challenge

### ISSUE THREAD

**Issue by tarkata** [Code-Fights/codefights-wiki#110]
Why can't I post any frontend challenge? No option to choose for HTML, CSS or JS, only programming languages are available.

**Comment by omegascorp** [comment]
Hi @tarkata ,

Currently we don't have a UI for posting front end challenge. But you can send me HTML, CSS and JS of your challenge via codepen.io or similar service and we will post it.

**Comment by tarkata** [comment]
That will be okay. (Y)
