### ISSUE TITLE
RegExp matches returning undefined when accessing length

### ISSUE THREAD

**Issue by aramys** [Code-Fights/codefights-wiki#116]
<img width="636" alt="screen shot 2017-04-15 at 8 51 27 pm" src="https://cloud.githubusercontent.com/assets/108946/25068600/8d64e726-221d-11e7-9ed3-d882618c22ba.png">
console.log(matches[1]); also returns undefined.
<img width="638" alt="screen shot 2017-04-15 at 8 51 42 pm" src="https://cloud.githubusercontent.com/assets/108946/25068601/8d6511ba-221d-11e7-8eee-7939c04e2d1a.png">

**Comment by aramys** [comment]
Odd, but I think I understand what was wrong here.

**Comment by Albinutte** [comment]
@aramys There are no parenthesis in the fifth test case, which is why `match` is `null` and `match.length` throws an error.

**Comment by aramys** [comment]
Yes I realized that immediately after posting.
