### ISSUE TITLE
Bots in Wiki should be updated

### ISSUE THREAD

**Issue by kokosek** [Code-Fights/codefights-wiki#3]
As you can see [here](https://github.com/Code-Fights/codefights-wiki/wiki/1.-General-FAQ#how-does-practice-work) the bots are outdated: all of them are Recruits, Integrus has a wrong name and the colors doesn't match those from Practice page.

**Comment by tigransloyan** [comment]
ha @kokosek good catch, the image you see on the FAQ is actually based off of a mock thus the mismatches you noticed. cc @jfdesroches

**Comment by kokosek** [comment]
Thanks, @tigransloyan.
I hope you don't mind if I copy all found bugs from CF forum here? And add every feature I can think of? Perhaps Github would be a good place for managing bugs and feature requests because of labels.

**Comment by tigransloyan** [comment]
@kokosek absolutely, please go for it. I think it would be a good idea to post each of those in a separate issue though so that we can track them.

**Comment by jfdesroches** [comment]
Thanks @kokosek I just updated the Practice room images :)

**Comment by kokosek** [comment]
@jfdesroches Thank *you*.
