### ISSUE TITLE
Winners in draws seem to be determined by random

### ISSUE THREAD

**Issue by kokosek** [Code-Fights/codefights-wiki#5]
In [this](https://goo.gl/jUNl8X) tournament user with higher XP won in a draw, while in [this](https://goo.gl/1z42kO) the less experienced one was the winner.
I know that in the first tournament it seems like user with less XP points won but at that time the other one (me) had lower XP.

I think random is unfair. Users should be able to deduce who wins in certain situations. It adds to the strategy as imo CodeFights is not only about finding bugs but also calculating your score and knowing where not to submit possible solution.

What I'd suggest is letting the user with lower XP win because if he managed to draw with a theoretically better opponent, he deserves it. And thus, more experienced user have to do a little bit better.
I'm not for implementing a fight loop (fighting until not a draw) because in the end it still has to be a limit in case users are afk or have bad intentions.

**Comment by tigransloyan** [comment]
@kokosek actually, since XP is not really a true indicator of strength we calculate a rating in the background (also used for matchmaking) and the system works exactly as you suggested just based on the rating and not the XP, i.e. those with a lower rating go through. But I do agree that it's confusing and hard to explain.

**Comment by kokosek** [comment]
Oh, so every user has another rank which is hidden? So theoretically, when somebody loses *every* fight and get to ninja by +X XP (for X < 99) after each fight, he'll be matched with a recruit or trainee instead of ninjas and captains?

**Comment by tigransloyan** [comment]
@kokosek theoretically, but in practice that can't happen because if you keep losing it would take you forever to get anywhere.

**Comment by kokosek** [comment]
It's not random and it's logical so I'm closing the issue.
