### ISSUE TITLE
In challenges, comments in codes not counted

### ISSUE THREAD

**Issue by kokosek** [Code-Fights/codefights-wiki#50]
If comments weren't considered when calculating code length, users would be able to explain their solutions if they wanted.

**Comment by MaurolepisDreki** [comment]
I concur, the engine does not count white space in the length of the code which allows some formatting to make the code more readable.  Compilers and interpreters treat comments as whitespace, so why shouldn't the challenge as well?  After all, documenting code is essential in programming and troubleshooting.

**Comment by kokosek** [comment]
It's been implemented so I'm closing the issue.
