### ISSUE TITLE
Include regex library in C++

### ISSUE THREAD

**Issue by kokosek** [Code-Fights/codefights-wiki#62]
In all languages except for C++ we can use regular expressions. I think adding regex library would be a good idea.

**Comment by tigransloyan** [comment]
@eduard-piliposyan is there any reason why? ^^

**Comment by eduard-piliposyan** [comment]
@tigransloyan actually regex is included and everyone can use it. 
following libraries are included for c++
#include <iostream>
#include <vector>
#include <cstdarg>
#include <string>
#include <cstdio>
#include <cctype>
#include <cmath>
#include <queue>
#include <map>
#include <set>
#include <algorithm>
#include <climits>
#include <sstream>
#include <numeric>
#include <iterator>
#include <iomanip>
#include <utility>
#include <stack>
#include <functional>
#include <deque>
#include <complex>
#include <bitset>
#include <list>
#include <array>
#include <regex>

**Comment by tigransloyan** [comment]
@kokosek so what made you think that regex is not enabled for C++?

**Comment by malinovsky239** [comment]
@tigransloyan @eduard-piliposyan We have gcc 4.8.4 (if we haven't updated compiler since I checked it last time), and regular expressions are supported starting from 4.9.

**Comment by eduard-piliposyan** [comment]
Thanks. I didn't know that @malinovsky239 
Strange that library is available but not fully supported.

**Comment by kokosek** [comment]
@tigransloyan Mr. Malinovsky explained the reason but as an example:
`error: no matching function for call to 'regex_replace(std::string&, std::regex&, const char [18])'`

**Comment by tigransloyan** [comment]
@kokosek this should be done
