### ISSUE TITLE
Mentioning users

### ISSUE THREAD

**Issue by kokosek** [Code-Fights/codefights-wiki#64]
We're able to mention multiple users in comments and posts *but* after the first mentioning we don't have the cool hints combobox so we have to write whole username ourselves.
However, and this is quite funny that it works :D, we are able to do it if... after the first mentioning we write a string ending with 's'. So for example if I write "@Test @Test2" I have to write "Test2" myself but if I write "@Test s @Test2" I can choose both from hint comboboxes. :D

// So what I'll do until it's fixed, I'll write @Sb s @Sb2 and then remove the s.

**Comment by tigransloyan** [comment]
@aram90 i have seen this too and it's quite annoying, any ideas?

**Comment by kokosek** [comment]
Seems fixed so I'm closing the issue.
