### ISSUE TITLE
Load failed: Unable to load notifications

### ISSUE THREAD

**Issue by kokosek** [Code-Fights/codefights-wiki#67]
When I clicked bell icon in the top right corner and then "SEE ALL" I was redirected [here](https://codefights.com/notifications) and got error from the title.

**Comment by tigransloyan** [comment]
@kokosek thanks for noticing this, the fix should go live soon.

**Comment by kokosek** [comment]
Seems fixed so I'm closing the issue.
I'll reopen if it reappears.
Thanks for fixing!
