### ISSUE TITLE
Last second and 5 seconds badges doesn't work

### ISSUE THREAD

**Issue by kokosek** [Code-Fights/codefights-wiki#7]
I've tried answering in the last second, as well as in the last 5 ones. My score was 51 (some time ago, when the scoring was different) and 50 (not so long ago). So even if I didn't submit in the last second (although I think I did) I 100% submitted in the last 5 seconds.
I've also tried Practice mode and didn't succeed as well.
It was a fight against random opponent.

One more user reported this problem on CF forum so it's not just me.
And I have 1/10 progress in 5 second badge so I it worked for me at the beginning.

**Comment by aram90** [comment]
@kokosek was that a friendly fight or a fight against random opponent? Badges are calculated only in fights against random opponents since friendly fights are not counted as competitive.

**Comment by kokosek** [comment]
@aram90 Ah, forgot to mention it for the 2nd time.
They were fights against random opponents.
I've updated bug description.

**Comment by kokosek** [comment]
I'm closing the issue since "last second" badges were removed.
