### ISSUE TITLE
Default language for challenges

### ISSUE THREAD

**Issue by kokosek** [Code-Fights/codefights-wiki#70]
For now, we can only choose default language for CodeFights and this language is also a default one for challenges. But some people may prefer Ruby over the 4 main lanugages and have to change the language with every challenge.

Author of the solution:
[Bao_nguyen](https://codefights.com/feed/tpqTSXsaXvKPyBun8)

**Comment by tigransloyan** [comment]
@kokosek a similar solution to this is coming soon.

**Comment by kokosek** [comment]
Sooner than I expected. :-)
Thanks for implementing, guys.
Closing.
