### ISSUE TITLE
Incorrect solution treated as skipped

### ISSUE THREAD

**Issue by kokosek** [Code-Fights/codefights-wiki#73]
I've been losing on purpose the first round for some time now (to get the "for winning after being at least 100 points down x50" badge) but after the recent update I can't get -25 points in the first round.
I'm adding a semicolon at the end of a random line, and click ctrl+enter until I run out of submissions. Then I see the old, reddish message "INCORRECT" and I get the ">" symbol in the circle instead of "X" one. I also get 0 points for the round. Negative points are necessary to get 8 badges so I'd bring them back.

**Comment by tigransloyan** [comment]
@kokosek negative scores are intentionally removed. Which badges are you referring to that require a negative score?

**Comment by kokosek** [comment]
@tigrandp 3 badges "for winning after being at least 100 points down" and 5 badges "for winning a fight after 300+ score difference".

**Comment by tigransloyan** [comment]
@kokosek btw you are mentioning the wrong tigran :) and to answer your question, being 100 points down doesn't mean 100 points negative, but the rules for those badges likely need updating anyways cause it was made when CF was fully real-time.

**Comment by kokosek** [comment]
@tigransloyan Oh, sorry for not mentioning you. Awkward.
As for the badges, I think that being at least 100 points down means that I need to be losing by 100+ points and then win. But it's still impossible. Because to be losing 100+ I need 2 rounds. So optimistically, the opponent will get 2x50 and I will 2x0. So I have only 1 round to get 101 points which is impossible.

**Comment by kokosek** [comment]
Badges "being at least x points down" have been removed so I'm closing the issue.
So much losing for nothing. :-(
