### ISSUE TITLE
Coins seem to have halved themselves over-night. 

### ISSUE THREAD

**Issue by BrandonTroche** [Code-Fights/codefights-wiki#83]
This is probably a novice thing to ask about the site, but I'm fairly new. My coins went from around 12.5k to 6.5k over night. I logged into my account on a different computer and saw the 6.5k after remembering being around 12.5k before going to sleep. I'm not sure if coins have a decay rate, or if you lose coins for not logging on for a while, but I had a concern about this.

**Comment by tigransloyan** [comment]
@BrandonTroche try refreshing the page or logging in/out see if that brings your coins back, we have heard a similar issue before and it's usually due to some caching problem.

**Comment by BrandonTroche** [comment]
Thanks, I'll give it a shot.
