### ISSUE TITLE
an object is undefined in javascript

### ISSUE THREAD

**Issue by aberthier** [Code-Fights/codefights-wiki#91]
the following javascript method:
```
function closestNeighbor(li) {
    li.sort((a,b)=> a - b);
    var r=[];l=li.length;
    li.forEach((v,i) =>{
        r.push({
            minDistance:Math.min(v-li[i-1], li[i+1]-v),
            value:v
        });
    })
    //console.log(li)
    r[0].minDistance = li[1]-li[0];
    r[l-1].minDistance=li[l-1]-li[l-2];
    r.sort((a,b)=>b.minDistance-a.minDistance);
    console.log(r[1].value)
    //var res = (r[0].value > r[1].value) ? r[1].value: r[0].value;
}
```

returns:
Execution error: Something went wrong when executing the solution - program stopped unexpectedly with an error.
Cannot read property 'value' of undefined

for the input: 
[2,3,4,4,11,5,1,9]

works fine in node or in the browser console

**Comment by Albinutte** [comment]
@aberthier not sure if `[1,1,0,0,2,1,1,2]` is what causes an error, try running your solution on something like `[42]` (i.e. 1-element list). I also don't see a `return` statement in your code.

**Comment by aberthier** [comment]
Sorry wrong input I just modified it.

The error occurs on the evaluation of the middle part of the array, not the edge cases (thus the r[1]).

I am encountering the error in the closestneighbor challenge.

![untitled](https://cloud.githubusercontent.com/assets/7230052/14275068/2324e770-fb69-11e5-82e4-9a3612cc14ea.png)

**Comment by Albinutte** [comment]
@aberthier yup I guessed that :)
>he error occurs on the evaluation of the middle part of the array, not the edge cases (thus the r[1]).

Not sure what you mean by that. Your solution is tested on all sample tests, including the one with only one element in `li`. Check this out: https://repl.it/CCVp/0, it fails with the same error as in our IDE.

**Comment by aberthier** [comment]
Yes you are right, I did not look at all the test cases, my bad, thank you, I will close.
